vtk_module(vtkFiltersGeometry
  GROUPS
    StandAlone
  DEPENDS
    vtkFiltersCore
  TEST_DEPENDS
    vtkIOXML
  vtkIOLegacy
    vtkRenderingOpenGL
    vtkTestingRendering
    vtkInteractionStyle
  )
